### ISSUE TITLE
请问我可否把你的ZYBannerView转到xamarin C#代码并公开在GitHub上

### ISSUE THREAD

**Issue by jingliancui** [zzyspace/ZYBannerView#13]
你好 ,我是用xamarin开发ios的，我的项目已经用了你的库了，我自己已经把他(ZYBannerView)转换为c#代码，我想把这份c#代码公开在GitHub上，你觉得如何？

**Comment by zzyspace** [comment]
可以的😁

**Comment by jingliancui** [comment]
谢谢你！ ^_^
已经好了
地址是这个 https://github.com/jingliancui/ZYBannerView_Xamarin

**Comment by zzyspace** [comment]
OK, 已经在 Readme 中加入了 `ZYBannerView_Xamarin` 的链接, 同时也谢谢你对这个项目的贡献 :)
