### ISSUE TITLE
view的位置在frame改变时会很奇怪

### ISSUE THREAD

**Issue by goodman-capu** [zzyspace/ZYBannerView#2]
例如ZYBannerView.m的78行
`if (CGRectEqualToRect(self.pageControl.frame, CGRectZero)) {
        // 若未对pageControl设置过frame, 则使用以下默认frame`
在frame改变时 pageControl的位置不会跟随变化
`updateSubviewsFrame`函数中也没用对collection view的frame进行刷新
是否意味着这个程序并不是很好地支持autolayout？

**Comment by zzyspace** [comment]
谢谢提醒, 已修复
