### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by goodman-capu** [zzyspace/ZYBannerView#3]
1. `scrollInterval` 属性并不能在 Interface Builder 中设计，是否不应该使用 `NSTimeInterval`？
2. Collection View 一开始只能右划不能左划

**Comment by zzyspace** [comment]
1. Xcode6中`NSTimeInterval`属性是可以在IB中配置的, Xcode7不知道出于什么原因不支持了. 之前使用`NSTimeInterval`的原因是它作为`scrollInterval`的类型更合适点. 不过为了适配Xcode7, 现已更改为`CGFloat`类型
2. 默认`shouldLoop`属性值为`NO`, 自然是不能右滑的, 设置`shouldLoop`属性为`YES`即可.
   最后, 谢谢你的建议 :)

**Comment by goodman-capu** [comment]
赞效率 顺便问一句 CocoaPods 上什么时候会更新版本呢

**Comment by zzyspace** [comment]
CocoaPods已更新至v0.1.3

**Comment by goodman-capu** [comment]
更新了后发现还是有小问题

```
- (void)setFrame:(CGRect)frame
{
    self.pageControl.frame = CGRectZero;
    [super setFrame:frame];
}

```

这种方法在AutoLayout中不起作用😂
