### ISSUE TITLE
让她自然滑动超过一定张数的时候，图片会有卡顿的现象

### ISSUE THREAD

**Issue by huayangyu** [zzyspace/ZYBannerView#5]

**Comment by zzyspace** [comment]
大概为多少张，是本地图片还是网络图片?

**Comment by huayangyu** [comment]
网络图片，我改了下代码，感觉是因为在ZYBannerView中的-collectionView:cellForItemAtIndexPath:中cell的subview是每次都alloc了；我直接把自定义的View写到源码的cell上了。

**Comment by zzyspace** [comment]
谢谢提醒, 已修复这个问题!
