### ISSUE TITLE
请问支持自动布局么

### ISSUE THREAD

**Issue by mxyolande** [zzyspace/ZYBannerView#6]
SDCycleScrollView这个轮子就是因为不支持自动布局。。我才不用的。

**Comment by zzyspace** [comment]
支持Autolayout的. 并且最新的v1.1.0版本已经优化了pageControl布局的问题.

**Comment by mxyolande** [comment]
您好, 希望您尽快更新pod

原始邮件
发件人:zy_zhangnotifications@github.com
收件人:zzyspace/ZYBannerViewZYBannerView@noreply.github.com
抄送:马旭mx_yolande@qq.com; Authorauthor@noreply.github.com
发送时间:2016年8月31日(周三) 13:44
主题:Re: [zzyspace/ZYBannerView] 请问支持自动布局么 (#6)

支持Autolayout的. 并且最新的v1.1.0版本已经优化了pageControl布局的问题.

**Comment by zzyspace** [comment]
已更新.
