### ISSUE TITLE
在 UITableView 中使用会卡顿。

### ISSUE THREAD

**Issue by stan-chuk** [zzyspace/ZYBannerView#9]
在 UITableView 中使用时，当轮播的控件被滑出屏幕再滑回来的时候会产生卡顿，因为 BannerView 又要重新初始构造化一次，有什么解决方案吗？谢谢。

**Comment by zzyspace** [comment]
建议让当前控制器持有 bannerView，这样就可以避免多次初始化。

**Comment by stan-chuk** [comment]
成功了，虽然不能复用，但是相对于性能来说好很多。
